# Generated by Django 4.2.7 on 2023-12-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='educator_pictures',
            fields=[
                ('mobile', models.CharField(max_length=11, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='media/static/')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
    ]
