# Generated by Django 4.2.7 on 2023-12-18 05:59

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educator_pictures',
            name='image',
            field=models.ImageField(upload_to='media/static/', validators=[app.models.validate_image_extension]),
        ),
    ]
