# Generated by Django 4.2.7 on 2023-12-18 10:27

import app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_educator_pictures_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseOverview',
            fields=[
                ('course_title', models.CharField(default='Some Course', max_length=100)),
                ('course_thumbnail', models.ImageField(upload_to='media/static/courses/course_thumbnails/', validators=[app.models.validate_image_extension])),
                ('course_description', models.CharField(default='No course description', max_length=250)),
                ('course_level', models.CharField(default='Intermediate', max_length=13)),
                ('course_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='media/videos/')),
                ('overview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courseoverview')),
            ],
        ),
        migrations.AlterField(
            model_name='educator_pictures',
            name='image',
            field=models.ImageField(upload_to='media/static/educator_profile_pictures/', validators=[app.models.validate_image_extension]),
        ),
        migrations.CreateModel(
            name='HeaderTitles',
            fields=[
                ('header', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('total_subcourses', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('header_desc', models.CharField(max_length=100)),
                ('header_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('overview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courseoverview')),
            ],
        ),
        migrations.CreateModel(
            name='VideoTitles',
            fields=[
                ('vid_title', models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(5)])),
                ('vid_length', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1800000)])),
                ('vid_id', models.OneToOneField(max_length=32, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.videos')),
                ('header_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.headertitles')),
                ('overview_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.courseoverview')),
            ],
        ),
    ]
